//tealium universal tag - utag.10 ut4.0.202409090936, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;var element;element=document.getElementById("utag_10");if(element){element.remove();}
if(utag===undefined){utag={};}
if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}
else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}
if(o.id){b.id=o.id;}
if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}
l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"struCustomerId":"customerId","struScriptUrl":"base_url"};u.extend=[function(a,b){try{if(1){if(a&&a==="view"){if(b.page_type&&b.page_type.toLowerCase()==="image"){return false;}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b.struScriptUrl="https://ak.sail-horizon.com/spm/spm.v1.min.js";b.struCustomerId="16d12e25531c01362680f31746e95b4a";if(b.tealium_environment&&b.tealium_environment.toLowerCase()==="prod"){b.struCustomerId="8758da6caa1753a00a823e7ce9e99354";}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){u.initialized=true;Sailthru.init({customerId:u.data.customerId,useStoredTags:false});};u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_10'});}};utag.o[loader].loader.LOAD(id);})("10","newsinternational.thesun.web.2017");}catch(error){utag.DB(error);}
